# -*- coding: utf-8 -*-
"""Correções Loop For.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VqFnO_-8lPHwjZhqdspsbsJitLbfWhih
"""

num = int(input('Digite um número: '))

for batata in range(1,11):
  print(f'A tabuada: {num} x {batata} = {num * batata} ')

"""# 1 - Desenvolva um programa que funcione da seguinte maneira:
# Solicite ao usuário que informe a quantidade total de pessoas em um grupo.
# Para cada pessoa, peça que o usuário registre o sexo, utilizando a letra 'm' ou 'M' para masculino.
# O programa deve contar e, ao final, exibir o total de pessoas do sexo masculino.

"""

qtd_pessoas = int(input('Digite a quantidade de pessoas: '))
contador = 0

for pessoa in range(qtd_pessoas):
  sexo = input(f'Digite o sexo da {pessoa+1}º pessoa: ')
  if sexo == 'm' or sexo == 'M':
    contador += 1
    # contador = contador + 1
print(f'A quantidade de pessoas do sexo masculino é {contador}')

"""# 2 - Construa um programa em Python utilizando os comandos aprendidos até agora para encontrar todos os números pares entre 1 e 100;

"""

for pares in range(101):
  if pares % 2 == 0:
    print(pares, end=' ')

"""# 3 - Faça um programa que leia 5 números e informe a soma e a média dos números;

"""

soma = 0

for batata in range(1,6):
  numero = int(input(f'Digite o {batata}º número: '))
  soma += numero
  media = soma/numero
print(f'A soma dos valores é {soma} e a média é {media}')

"""# 4.   Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações.

"""

tentativa = 3

for i in range(3):
  nome = input('Digite seu nome: ')
  senha = input('Digite sua senha: ')
  if nome == senha:
    tentativa -= 1
    print(f'Senha e nome não podem ser iguais!Você tem {tentativa} tentativas')
  else:
    print('Acesso liberado')
    break
else:
  print('Redefina a senha')