# -*- coding: utf-8 -*-
"""Correção Exercícios Dicionário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7BQ6bCmgHVn7fY0G9fGxGaKQybmpyyT

# 1 - Crie um dicionário com informações de um aluno (nome, idade e curso). Em seguida, adicione o campo 'nota' ao dicionário.
"""

aluno = {
    'nome': 'João Silva',
    'idade': 21,
    'curso': 'Engenharia'
}

aluno['nota'] = 8.7

print(aluno)

"""# 2 - Crie um dicionário com 3 produtos e seus preços. Mostre o preço do produto 1."""

produtos = {
    'produto_1': 10,
    'produto_2': 20,
    'produto_3': 30
}

print(f"O preço do Produto 1 é: R${produtos['produto_1']}")

"""# 3 - Remova o produto 2 do dicionário e mostre o dicionário atualizado."""

produtos = {
    'produto_1': 10,
    'produto_2': 20,
    'produto_3': 30
}

del produtos['produto_2']

print(produtos)

dic1 = {'nome':'Ricardo',
        'aula':'Python'}

local = {'cidade':'São Paulo',
        'bairro':'Ipiranga'}

backup = dic1.copy()
print(backup)
dic1.update(local)
print(dic1)
print(len(dic1))