# -*- coding: utf-8 -*-
"""Correções Exercícios Função.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NOhEcvGVfKoNUp3KJHVB_qV1Fb44fF_z

# 1 - Crie uma função que receba dois números e retorne a soma deles.
"""

def soma(a,b):
  return a + b

num1 = int(input('Digite o primeiro número: '))
num2 = int(input('Digite o segundo número: '))

resultado = soma(num1,num2)
print(f'O resultado da soma de {num1} + {num2} = {resultado}')

"""# 2 - Crie uma função que receba um número e retorne True se ele for par, e False caso contrário.

"""

def is_par(batata):
  if batata % 2 == 0:
    return True
  else:
    return False

num1 = int(input('Digite um número: '))

print(is_par(num1))

"""# 3 - Crie uma função que converta uma temperatura de Celsius para Fahrenheit.

"""

def c_to_f(batata):
  return (batata * 9/5) + 32

num = float(input('Digite a temperatura em °C: '))

print(f'A temperatura em °F é {c_to_f(num)}')