# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rMK8EHVVhzMYbhapFTK2J6RKgbA6kfU-
"""

import csv
def nome_existente(nome):
    with open('usuarios.csv', mode='r', newline='') as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            if row[0] == nome:
                return True
    return False
def senha_existente(senha):
    with open('usuarios.csv', mode='r', newline='') as file:
        reader = csv.reader(file)
        next(reader)
        for row in reader:
            if row[1] == senha:
                return True
    return False
with open('usuarios.csv', mode='a', newline='') as file:
    writer = csv.writer(file)
    if file.tell() == 0:
        writer.writerow(['Nome', 'Senha'])

    while True:
        nome = input('Digite seu nome (ou "fim" para encerrar): ')

        if nome.lower() == 'fim':
            print('Encerrando...')
            break

        if nome_existente(nome):
            print(f'O nome "{nome}" já está registrado. Por favor, escolha outro nome.')
            continue
        print(f'Nome: {nome}')


        senha = input('Digite sua senha: ')


        if senha_existente(senha):
            print(f'A senha "{senha}" já foi utilizada. Por favor, escolha outra senha.')
            continue

        senha3 = input('Digite sua senha novamente: ')

        if senha == senha3:
            if senha != "":

                writer.writerow([nome, senha])
                print('Senha válida e dados salvos.')
            else:
                print('A senha não pode estar vazia.')
        else:
            print('As senhas não coincidem. Tente novamente.')