# -*- coding: utf-8 -*-
"""Correção Exercícios Tuplas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Beo6vCg3WyYIBflKZy4I7ysYoPZC1wmc

# 1 - Crie uma tupla com 4 números inteiros e mostre o segundo número do index.
"""

numeros = (1,2,3,4)
print(f'O segundo número do index é {numeros[2]}.')

"""# 2 - Crie duas tuplas com diferentes tipos de dados (ex: números e strings). Imprima o index 2 da tupla de números e o index 3 da tupla de string no mesmo print."""

numeros = (1,2,3,4)
letras = ['a','b','c','d']

print(f'O index 2 da tupla de números é {numeros[2]} e o index 3 da tupla de letras é {letras[-1]}')

"""# 3 - Crie uma tupla numeros = (5, 10, 15, 20) e converta-a em uma lista. Adicione o número 25 à lista resultante."""

numeros = (5, 10, 15, 20)

numeros_lista = list(numeros)
numeros_lista.append(25)
numeros_tupla = tuple(numeros_lista)

print(numeros_tupla)